language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-fulltest-app
  api_key:
    secure: OBSxebYuHisejgoMWJL/g6iCxV8fBD9+yYdLswnuZD7bxn1qxvJOrpIkqOW/Fu8nVlzB76S5VcYTBxN/X50ihb9LLN1rMta5zzVbFmiyV79Lu2LSWzDLnDlLys1jsL+UrDVqPtpOKCiCKlXe6X7KVh0EqskwgPodXUds2uJRwcVuFJXHMmwlCh9mu6cjS/UjNZ9/LVOj9MAtltihdQoP5Y7w3a/o0lL42LIEUnmpnv0aK9AkCGqOHgzXBFXepPRKyeOLf011FuctNY9TQH/UOczabQ233Ew1+yWq3RHC58fbu++c4MGb/7VvpkDnqDvoZULbNV3XKFyMpsvwi2aaGwxJDiAprRfP6yjw3OXTIFBwuHZ8SzjcnjDDWoM1Y2ITmtu32w76l2Fkke5IIrd3ykOdYYyWFYAdzBM3sUrUBYdrJ7OYo8olIQOh3Y5YrSZuGqA7KOV0SkLqyEvwuzvohy/81v/wd8oVX1f0VAzSy1xqzU9SJ5ETutrnaN+kwDplYYVhlA5yOWO8BsAPufeEPZaXeSM7mvvLP8+l7PrVX7fgtq+q5mGyy06KYdo2+TaZnmGIdTIdeeqENVwLRquilZJf6aFJLgnYE3v9lZjujZBrNxWH7qP0Bc50Wx+T3jaMPUruM+DftlzOVCzFd5j6sFD8oKjn3K55T1C2YlSCyvI=
  on:
    repo: degreeproject/react-fulltest-app
    branch: master
