language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-fulltest-app
  api_key:
    secure: Qe1uokapkhZeOpGEZKc7C8sv3k12nvy1lS9IFYQ3N1ayOrMv/RzkITDK84Cbc93IpFUXap/6s2Rqkp+WjRlek0XuZZfA39ONmovWrz7iDaxPbS6VFSO/K+dOtnl04EOeztVtwbcRU47Pfx0150K7PYXuMx++HOxL9rF0HWnaZu7YvHM+f3WoWnWveAveyIoL4DUjZ3Bw5NatolCmKDSf8DLp8gftOLiNy0TAchRteOogXfAFgmaADKNbCwsVJj9hG05CtLExTuUr6MNmVEBn8Q6Fv7SQE4DJuEq7ngC13+wlz+/09PectCeiug/+CPIl57uzUX9YxBskbJpza5Li3K377925CgBWdJ2lILW5RKr6+GkJ1mPZVZCHx+Oa1M2ytXnFuK8pvnD6EQm2HU6DWr2J9/0D9a5MVQRHQA2W665a57QqAGDwnNRgBGFaZoR65aaTGjhnuuuX6PgJXk8tjW0BNFxpZPm/gsktGzVz/wxD6fcapM+rt3f75QToxkOZVzYNiGdIJzdnvq1jYKhRqyKo9aAdwmN/VIWMBbJ1wDDMyBM4lXEu9zit26oVH4RrC6xuG1GZYP9tItpsx8lBYiGHzFV1KM+cdsf/idlwJ2g3qb/duiOSc73kpowj8OQKI4CAn4Qhq/nmTcipWk8OPJePg4dLKyg70NANtu8spqI=
  on:
    repo: degreeproject/react-fulltest-app
    branch: master
