language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-fulltest-app
  api_key:
    secure: AzgmER20x6kc0xWGrCiRp5OBnd2nzjLNM0rqFd0WaPg4998cbVizBC0z39thzob/AhnLvJtDUYkc0H3LXGh3Z0foz8uWspJ0SUk4nbMDTHXhQfxR899g6TeKJYeULF9qncs8SFQbQZffC1DsQLDEUwDzUVUzOiEh+2Re5jNRj/ILLxIsV2BjYNj3JYvnAkuPBQaWwcgEnrzimMb9RgVmRKSC1ULrf785sgHKBIWp6V43tBqB4DwY0Wl1PO+TOUSrvXZdUe6LVOfMMK4PvUzk1RuRQe5rWwWBfvz6gEmJjbGBCorevnLlDDi5HMVGCh5Chi5v/e8I6D77P31OfLhkTO4wJUVfTiJtJc1p7CfZUqGJAatSITvP4odXQaepzllJ0Yorf8iUeVQW6gfomt1xCc/y0Qsrtax7nvOeX3WHJ2E3IUJHganvezcdivu1dizEQ92Lj0xpBi6MSpTedDEwpqWGfG812m8VV8jZUCNs3zK839arCC3HlVbW2sNH0ZbziQN0IYliXAjsKYDHMb7MK/mlozo6Yd1V3rd0FWbly1t0NoOEM9DBO/nPWegs1509CebulrgHi7aIHj351Brk7Ycs7RHAyaezEq3CZ7IlgyaLap6j4EPdV44wfe0FMdgSMrsokWCXApPwpkcJYEOyivexbw1vd60QldPJQwyb2j8=
  on:
    repo: degreeproject/react-fulltest-app
    branch: master
