language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-fulltest-app
  api_key:
    secure: 0Csidf+JE1I7KCgcUXJw+xq1H50Oz0pYBIP5T7lA+qV1XFxu0q/VwEGWHQQj8eXxkfFeQdVux/dmpAcsw0tJKeNd4PeMCvi3DcyuaOHGy9OM+Y8qYGdVH0JB+KGHUiRsrhhs5dqazlCMsiI8jvpzsNZjT87gxWXi3MPVslweIa+q8JnHEOwz3YQ1c9ECb8Gi7AbU155pQMI/PF/pjgE6kcT/0+vhBKQwI2MaBWtEWaZHICT5nKNZzoxtwRv+xXYxo5+gvbgpE23BcGdWcTe7dnN2FcMiC3gaiiFyMuV4GC5Vj/y0G9n42hh3Qh2aN2pgs8UDjcseFt61lNN3iR/Tuew0Xq+yk8aiRF1LWOBFvxqHIBwnTE2FYLKkj/8tbSJxnFyfLRhka3oSKQb+uI5dgkApWnViktqd2b7C1kM765NcL5ioFn9mdbJGvMrfnHWXjdRBMrNoMzdlrWUXDhW7z3LNUfTkFGIxGf+MJBpRagBK4j/0ZlgAdwONq7gIyPTXvhSsNgxzzf/r9B6GeM7LAnY5kDVubt1UjjxQAQB6E5fthy0YKrw6qwDK+nZmEpghgQOp1i0NwcF6rEaIksQKe15QH3MZ4/CtXeXnfMglowQiKOjgwxIxsGfOseOR8AlCl/B3QDw2AWPGXlzthE5EhBmr7/Lg4tvsDT5xqjxjTwc=
  on:
    repo: degreeproject/react-fulltest-app
    branch: master
