language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-fulltest-app
  api_key:
    secure: vCdAnuHlR+TvEoBbGtMwYvJuhHF0cEO0DHYQrYHr+vvcW/yZrPHFD8t0I2E25bpuZL5BPU4izqII+A+hTn7cEaaHJvAiWVqaqC8oMiR+/xXjfQPwbZVPjby4f6WxAV9yciqyQA9CmqGG3FptWP+sZohE/Xng+xCAt5zxUjoeH6AXIg3OonxqeBAoT2WK4A9fm3msItAqUHjiJwr8L7+26+E/KcPr+IubK5GYitzi1kdWQbU+Ht5150KdSFdXF2uR+Q7G+pJzqGr7haSasP/lKZXarlE1S34Ds9d7RAVzyVtOfsSOoiLm3RwOoXPo5bDzga8mfps3y+so1NV56RrFjuRb9sQ7RLd72nwzOfs1MZalz89ggXRWxWJOjUnNZvRDsd+mthzaZSNjVTd2yaqAqlhMuYWQxeNY8yfJaIMnYYIRMCS2hGiPgJFrmo3R3UFCPt10ty2ex+xbdGVKRnH0OC5L76KpdD+UG0ACtZXdjnpqYoeE5RcG4Sd5Z2z3MlI6gAzSbr142RlYRu0Hwy0dUqYTFIXy8Vwipw/40ucjWM/mcWHwH9Dk62zCNXWfoJ79JUWO+SEea+N2srYtqKhjVS8dgqJOpPea3NMY0kZMgrXjZxEqToyVmqBvwXEZSLvAqEcS4hlXJf6kdGJLmvnFGKFJFsepkmEaYWhtE5HyUM8=
  on:
    repo: degreeproject/react-fulltest-app
    branch: master
